# -*- coding: utf-8 -*-
"""Project1stexample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1TpHlCrIV-v9eEiAuSKLG7JDxnLpTGV
"""

!pip install transformers torch accelerate pandas matplotlib

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load the Model
# We use a smaller, instruction-tuned Granite model that runs well in Colab
model_id = "ibm-granite/granite-3.0-3b-a800m-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True  # Required for this model
)

# 2. Create a text-generation pipeline
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=10  # We only need a single word (Positive/Negative/Neutral)
)

# 3. Define a function to classify sentiment
def classify_sentiment(review_text):
    # This is a simple "zero-shot" prompt
    prompt = f"""Classify the sentiment of the following review as Positive, Negative, or Neutral.
Review: "{review_text}"
Sentiment:"""

    response = generator(prompt, pad_token_id=tokenizer.eos_token_id)

    # Clean up the output to get just the sentiment
    try:
        sentiment = response[0]['generated_text'].split("Sentiment:")[1].strip()
        # Handle cases where the model might add extra text
        if "Positive" in sentiment:
            return "Positive"
        if "Negative" in sentiment:
            return "Negative"
        if "Neutral" in sentiment:
            return "Neutral"
    except Exception as e:
        print(f"Error processing response: {e}")
        return "Neutral" # Default to Neutral on error
    return "Neutral"

# 4. Our sample data
reviews = [
    "I absolutely loved the service! Definitely coming back.",
    "The item arrived damaged, very disappointed.",
    "Average product. Nothing too exciting.",
    "Superb experience, exceeded all expectations!",
    "Not worth the money, poor quality.",
    "It was okay. Did the job.",
    "The best purchase I've made all year!",
    "Customer support was terrible and very slow."
]

# 5. Analyze the reviews
sentiments = [classify_sentiment(review) for review in reviews]

# 6. Create a DataFrame to hold the results
df = pd.DataFrame({
    'review': reviews,
    'sentiment': sentiments
})

print("Sentiment Analysis Results:")
print(df)

# 7. Generate the graph
print("\nGenerating graph...")

sentiment_counts = df['sentiment'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(
    sentiment_counts,
    labels=sentiment_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['#66bb6a', '#ef5350', '#ffca28'] # Green, Red, Amber
)
plt.title('Sentiment Distribution of Reviews (Analyzed by Granite)')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()