# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYm8ONIJcLFHCPC8dyqQd896_9_EaZd9
"""

"""Copy of Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbsbSjnJ9J7rYjdTREm6GBnB_lU5szCm
"""


!pip install matplotlib numpy pillow scikit-image --quiet

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from skimage import exposure
from google.colab import files

print("Upload your ocean image (JPG/PNG):")
uploaded = files.upload()
for fn in uploaded.keys():
    image_path = fn
print(f"✅ Uploaded: {image_path}")

img = Image.open(image_path)
img_np = np.array(img)
green_channel = img_np[:,:,1].astype(float) if img_np.ndim==3 else img_np.astype(float)

chl_map = exposure.equalize_adapthist(green_channel/255.0)

def simulate_productivity(chl_map, months, seasonality=True, variability=True):
    sim_map = chl_map.copy()
    maps = []
    for i in range(months):
        seasonal_factor = 1 + 0.05*np.sin(2*np.pi*i/12) if seasonality else 1
        random_factor = 1 + (np.random.normal(0,0.05, sim_map.shape) if variability else 1)
        sim_map = np.clip(sim_map*seasonal_factor*random_factor, 0, 1)
        if (i+1) % 12 == 0:
            maps.append(sim_map.copy())
    return maps  # list of yearly maps

def get_level_map(chl_map):
    level_map = np.empty(chl_map.shape, dtype=object)
    level_map[chl_map>0.6] = "High"
    level_map[(chl_map>0.3) & (chl_map<=0.6)] = "Moderate"
    level_map[chl_map<=0.3] = "Low"
    return level_map

def color_map(level_map):
    cmap = np.zeros(level_map.shape + (3,), dtype=float)
    cmap[level_map=="High"] = [0,1,0]       # Green
    cmap[level_map=="Moderate"] = [1,1,0]   # Yellow
    cmap[level_map=="Low"] = [1,0,0]        # Red
    return cmap

def show_map_and_hist(chl_map, title):
    level_map = get_level_map(chl_map)
    cmap = color_map(level_map)

    plt.figure(figsize=(8,6))
    plt.imshow(cmap)
    plt.title(title)
    plt.axis('off')
    plt.show()

    # Histogram
    plt.figure(figsize=(8,5))
    plt.hist(chl_map.flatten(), bins=50, color='skyblue', edgecolor='black')
    plt.axvline(0.3, color='red', linestyle='--', label='Low/Moderate Threshold')
    plt.axvline(0.6, color='green', linestyle='--', label='Moderate/High Threshold')
    plt.xlabel("Normalized Productivity")
    plt.ylabel("Pixel Count")
    plt.title(f"Productivity Distribution: {title}")
    plt.legend()
    plt.show()

    mean_val = np.nanmean(chl_map)
    if mean_val > 0.6:
        overall = "High Productivity 🌊"
    elif mean_val > 0.3:
        overall = "Moderate Productivity 🌊"
    else:
        overall = "Low Productivity ⚠️"
    print(f"📊 Overall Productivity ({title}): {overall}, Mean Value: {mean_val:.3f}")

show_map_and_hist(chl_map, "Current Ocean Productivity")

maps_3yr = simulate_productivity(chl_map, months=36)   # 3 years
maps_5yr = simulate_productivity(chl_map, months=60)   # 5 years
maps_10yr = simulate_productivity(chl_map, months=120) # 10 years

show_map_and_hist(maps_3yr[-1], "Forecasted Productivity: 3 Years")
show_map_and_hist(maps_5yr[-1], "Forecasted Productivity: 5 Years")
show_map_and_hist(maps_10yr[-1], "Forecasted Productivity: 10 Years")